repos:
  #  standard pre-commit hooks. You should probable keep all these hooks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files               #  prevents giant files from being committed.
      - id: check-ast                             #  simply checks whether the files parse as valid python.
      - id: check-builtin-literals                #  requires literal syntax when initializing empty or zero python builtin types.
      - id: check-case-conflict                   #  checks for files that would conflict in case-insensitive filesystems.
      - id: check-docstring-first                 #  checks a common error of defining a docstring after code.
      - id: check-executables-have-shebangs       #  ensures that (non-binary) executables have a shebang.
      - id: check-json                            #  checks json files for parseable syntax.
      - id: check-shebang-scripts-are-executable  #  ensures that (non-binary) files with a shebang are executable.
      - id: pretty-format-json                    #  sets a standard for formatting json files.
        args: [--no-sort-keys, --autofix]
      - id: check-merge-conflict                  #  checks for files that contain merge conflict strings.
      - id: check-symlinks                        #  checks for symlinks which do not point to anything.
      - id: check-xml                             #  checks xml files for parseable syntax.
      - id: check-yaml                            #  checks yaml files for parseable syntax.
      - id: destroyed-symlinks                    #  detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-private-key                    #  detects the presence of private keys.
      - id: end-of-file-fixer                     #  ensures that a file is either empty, or ends with one newline.
      - id: fix-byte-order-marker                 #  removes utf-8 byte order marker.
      - id: mixed-line-ending                     #  replaces or checks mixed line ending.
      - id: no-commit-to-branch                   #  don't commit to branch
        args: [--branch, master]                  #  default but be explicit, override when needed
      - id: requirements-txt-fixer                #  sorts entries in requirements.txt.
      - id: trailing-whitespace                   #  trims trailing whitespace.

  #  checks for possible leaking of secrets. You should probably not remove this hook.
  - repo: https://github.com/Yelp/detect-secrets
    rev: 'v1.4.0'
    hooks:
      - id: detect-secrets
        exclude: 'domains\/?[^\/]+.yaml$' #  exclude all yaml files in domains directory

  #  static code analysis for infrastructure as code misconfigurations (e.g. Terraform, Docker, Kubernetes)
  #  also another check for secrets
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.260'
    hooks:
      - id: checkov
        entry: >
          checkov -d .
          --skip-check CKV_DOCKER_2
          --skip-check CKV_AZURE_112
          --skip-check CKV2_AZURE_32
          --skip-check CKV_AZURE_40
          --skip-check CKV_AZURE_33
          --skip-check CKV_AZURE_59
          --skip-check CKV2_AZURE_33
          --skip-check CKV2_AZURE_21
          --skip-check CKV_AZURE_244
          --skip-check CKV2_AZURE_1
      - id: checkov_secrets

  #  analysis of your markdown files, configuration can be set in .markdownlint.yaml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix

  #  analysis of your Dockerfiles, configuration can be set in .hadolint.yaml
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint

  #  analysis of your shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck

  #  linter for yaml files, configuration can be set in .yamllint.yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint

  #  extra hooks, disable the hooks that are not needed

  #  analysis and formatting of terraform files, include this when using terraform
  #  see https://github.com/antonbabenko/pre-commit-terraform#table-of-content for documentation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        files: \.tf$
        args:
          - '--args=--var-file=terraform.tfvars'

  #  security scanner for terraform files, include this when using terraform
  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.1
    hooks:
      - id: tfsec-system

  #  hook for checking and formatting nomad files
  - repo: https://dev.azure.com/magister/Magister%20Public/_git/nomad-precommit-hooks
    rev: v0.0.1
    hooks:
      - id: nomad_fmt
